### ISSUE TITLE
CRAN?

### ISSUE THREAD

**Issue by gerwathome** [johnbaums/hues#1]
This is a useful tool.  It would be nice if you would submit it to CRAN.

**Comment by johnbaums** [comment]
Thanks @gerwathome - I plan to clean it up and submit it in the next few weeks. Sorry for the slow reply - sometimes my notifications get swamped by notifications for other repos I'm watching.

**Comment by johnbaums** [comment]
@gerwathome - [hues v0.1](https://github.com/johnbaums/hues/tree/v0.1) is now on [CRAN](https://cran.r-project.org/package=hues).
