### ISSUE TITLE
Support ggplot2 directly

### ISSUE THREAD

**Issue by rdinnager** [johnbaums/hues#3]
It would be useful to produce `scale_colour_hues()` / `scale_fill_hues()` functions for use with `ggplot2`. I don't know if you accept contributions, but I could make a pull request for this functionality if you are interested.  I'm thinking something like `scale_colour_brewer()` or `scale_colour_scico()` (from https://github.com/thomasp85/scico).

**Comment by johnbaums** [comment]
Thanks @rdinnager, good idea. And yep, happy to accept a PR if you're still interested.

**Comment by rdinnager** [comment]
Thanks for the reply @johnbaums . I'm fairly busy at the moment, but I will see if I can look into adding this in a couple weeks. Its something I'm interested in using myself, so I will try and get to it at some point anyway.
